### PR TITLE
Added .NET 7 + aligned other versions

### PR DESCRIPTION
**Pull request by jorgenbosman**

### CODE REVIEW

**Comment by picrap** [comment]
Thank you for your contribution. I don’t know why it takes more than 60mn to build but I’m currently reluctant to merge the pull request because of this.
Could you try to identify and fix the problem ?

**Comment by picrap** [comment]
Relates to #189

**Comment by jorgenbosman** [comment]
I have no idea how this appveyor is setup and if it supports .net 7? There is no error message or indication what the issue could be. It builds just fine locally...

**Comment by picrap** [comment]
Also you removed support for `netstandard2.0`, was it a problem? (someone specifically asked for it)

**Comment by jorgenbosman** [comment]
I've re-added the netstandard-2.0, but could you please try changing your appveyer build machine to VS2022?

**Comment by picrap** [comment]
You can do this by changing the `appveyor.yml`

**Pull request closed without merging**
