### PR TITLE
Support .NET 9

### PR DESCRIPTION
**Pull request by rgroenewoudt**
Add target .NET 9.
I also modified `MrAdvice.targets` to fallback to the latest supported .NET so it will keep working when .NET 10 is released.

### CODE REVIEW

**Comment by rgroenewoudt** [comment]
Build is failing with `NETSDK1223: Targeting .NET 9.0 or higher in Visual Studio 2022 17.11 is not supported.`.
The `image: Visual Studio 2022` still points to 17.10.

**Comment by picrap** [comment]
Thank you. Let’s wait until they update their build machines.

**Comment by SaifAqqad** [comment]
What's the timeline on this being merged?

**Comment by picrap** [comment]
We need to wait for a valid build. MrAdvice deployment relies on AppVeyor, so a merge now would not help. It will probably work before the end of the week.

**Comment by SaifAqqad** [comment]
awaiting appveyor/build-images#162

**Comment by picrap** [comment]
They finally updated appveyor configurations. MrAdvice 2.17 with dotnet 9 support is out! 🥳

**Pull request merged**
